#!/usr/bin/env python
import findrox; findrox.version(1, 9, 13)
import rox, os, sys

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))


import volume
if len(sys.argv) > 1:
	main = volume.Volume(sys.argv[1])
else:
	main = volume.Volume(1)

main.show_all()
rox.mainloop()
