#!/usr/bin/env python
try:
	import findrox; findrox.version(2,0,0)
	import rox, os, sys

	__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

	from optparse import OptionParser

	parser = OptionParser()
	parser.add_option("--mixer-options",
		action="store_true", dest="mix_options", default=False,
		help="display mixer options dialog")
	parser.add_option("--volume-options",
		action="store_true", dest="vol_options", default=False,
		help="display volume options dialog")

	(options, args) = parser.parse_args()

	if options.mix_options:
		import mixer
		rox.edit_options(rox.app_dir+'/Mixer.xml')
	elif options.vol_options:
		import volume
		rox.edit_options(rox.app_dir+'/Options.xml')
	else:
		import mixer
		main = mixer.Mixer()
		main.show()

	rox.mainloop()
except:
	rox.report_exception()

